import { Typography, Grid, Button } from "@material-ui/core";
import Head from "next/head";
import Link from "next/link";

export default function Blog() {
  return (
    <div>
      <Head>
        <title>VND</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-sm.ico" type="image/x-icon" />
      </Head>
      <Grid direction="column" align="center">
        <Typography variant="h4" color="textPrimary">
          Blog
        </Typography>
        <Link href="/blog">
          <Button variant="contained" color="Primary">
            View My Blog
          </Button>
        </Link>
      </Grid>
    </div>
  );
}
