import { Typography, Grid, Button, makeStyles, Paper } from "@material-ui/core";
import Head from "next/head";
import Link from "next/link";

const useStyles = makeStyles((theme) => ({
  root: {
    height: "100vh",
  },
}));

export default function Blog() {
  const classes = useStyles();

  return (
    <>
      <Head>
        <title>VND</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-sm.ico" type="image/x-icon" />
      </Head>
      <Paper className={classes.root}>
        <Grid direction="column" align="center">
          <Typography variant="h4" color="textPrimary">
            Blog
          </Typography>
          <Link href="/blog">
            <Button variant="contained" color="Primary">
              View My Blog
            </Button>
          </Link>
        </Grid>
      </Paper>
    </>
  );
}
