import Head from "next/head";
import Image from "next/image";
import "@fontsource/roboto";
import "@fontsource/lobster";
import SocialFloat from "../components/socialFloat";
import About from "../components/About";
import { useState, useEffect } from "react";
import { Collapse } from "@material-ui/core";
import Projects from "./projects";

import {
  Button,
  Container,
  Grid,
  Flex,
  Typography,
  Paper,
  Divider,
} from "@material-ui/core";
import Link from "next/link";
import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
  root: {
    height: "100vh",
    backgroundImage: "url(/pexels-athena-2582937.jpg)",
    backgroundRepeat: "none",
    backgroundSize: "cover",
  },
  homeText: {
    fontFamily: "lobster",
    fontWeight: "200",
  },
  container: {
    height: "100vh",
  },
  aboutSection: {
    margin: "5%",
    backgroundColor: "rgba(0,0,0,0.2)",

  }
}));

export default function Home() {
  const classes = useStyles();
  const [load, setLoad] = useState(false);
  useEffect(() => {
    setLoad(true);
  }, []);

  return (
    <div>
      <Head>
        <title>VND</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-sm.ico" type="image/x-icon" />
      </Head>
      <Paper className={classes.root}>
        <SocialFloat />
        <Grid container direction="column" align="center" className={classes.container}>
          <Collapse in={load} timeout={load ? 4000 : 0} collapsedHeight={0}>
            <Typography
              variant="h4"
              color="textPrimary"
              className={classes.homeText}
              gutterBottom
            >
              Father. <br />
              Developer. <br />
              Life Long Learner.
            </Typography></Collapse>
          <Divider />
          <Collapse in={load} timeout={load ? 2000 : 0} collapsedHeight={0}>
            <Grid item className={classes.aboutSection}>
              <About />
            </Grid>
          </Collapse>
        </Grid>
        <Projects className={classes.container} />
      </Paper>
    </div >
  );
}
